"""new field in user model

Revision ID: 48345cb38e57
Revises: d8f08fdc3544
Create Date: 2018-02-21 01:04:45.534561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48345cb38e57'
down_revision = 'd8f08fdc3544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
